### PR TITLE
Adding support for null-safety.

### PR DESCRIPTION
**Pull request by SalahAdDin**

### CODE REVIEW

**Comment by SahilHemnani777** [comment]
This PR should be merger asap- developers are shifting to null safety.

**Comment by SalahAdDin** [comment]
@SahilHemnani777 If you can review it we could help to @RyuuKenshi

**Comment by RyuuKenshi** [comment]
Thanks a lot @SalahAdDin for the help. 
Really appreciate the fact that people are using this package and now you guys are also upgrading it.
I made this package on a whim and never expected to get such a good response.

Thanks a lot guys.

**Comment by RyuuKenshi** [comment]
The new version supporting null-safety is now live on pub.dev. @SalahAdDin  @SahilHemnani777

**Pull request merged**
