### PR TITLE
didUpdateWidget has been added

### PR DESCRIPTION
**Pull request by taylanyildiz**
didUpdateWidget has been added to listen isCollapsed and animate

### CODE REVIEW

**Comment by RyuuKenshi** [comment]
Hi @taylanyildiz, thanks a lot for contributing to this project.
I think the didUpdateWidget() should be a private function.
Could you make the appropriate changes and also add a few lines of comments on this new function.
It will help future devs while working on it.

**Comment by taylanyildiz** [comment]
Hi @RyuuKenshi  thanks for your comment,
I did what you want and also  I added a record in README.md for responsive ui

**Comment by taylanyildiz** [comment]
@RyuuKenshi 
Also, if you want, we can provide users with a more customizable structure, for example, adding items should not only consist of title and icon, and of course, the avatar feature should be removed and a header should be added instead and it should be open to customization.

**Comment by RyuuKenshi** [comment]
@taylanyildiz 
Thanks a lot for the contribution. I have merged the code and updated it on pub.dev as well.
I really like your suggestion on adding more customizable structure. At the moment I am going through some financial problems and am not being able to concentrate on upgrading this repository.

If you like you can always add new features to this repository as a pull request. I would gladly review them and merge.

Thanks once again for contributing to this project.

**Pull request merged**
